### PR TITLE
Hungarian translation

### PR DESCRIPTION
**Pull request by lna91**
I wrote the hungarian translations of strings.xml, theme-options.xml, FullDescription.txt and ShortDescription.txt based of of the english and german versions already available. I followed the naming pattern of the folders.

### CODE REVIEW

**Comment by smithdtyler** [comment]
Hey, why was this closed? I've been planning to accept it, just haven't had time yet. Unless there was a reason to close it, I'll merge it in shortly.

**Comment by smithdtyler** [comment]
Unless you reply to clarify why this was closed, I'll have to assume something weird went wrong and discard this ticket.

**Comment by lna91** [comment]
Sorry, I thought that you don't really work on this anymore. Everything should be OK with the translations.

**Comment by smithdtyler** [comment]
OK, thanks! I'll accept the request :)

**Comment by smithdtyler** [comment]
This commit is included in release 3.3.3

**Pull request merged**
